export type DishLocale = "fr" | "en";

type Localized = { fr: string; en: string };

export type DishIngredient = {
  name: Localized;
  quantity: string;
  role: "base" | "protein" | "vegetable" | "spice" | "fat" | "side";
  optional?: boolean;
};

export type CulinaryDish = {
  slug: string;
  name: Localized;
  aliases: string[];
  country: string;
  region: string;
  category: "main" | "sauce" | "grill" | "street-food";
  difficulty: "easy" | "medium" | "hard";
  timeMinutes: number;
  servings: number;
  featured?: boolean;
  description: Localized;
  tradition: Localized;
  service: Localized;
  allergens: Localized[];
  tags: string[];
  productKeywords: string[];
  ingredients: DishIngredient[];
  steps: Localized[];
};

const l = (fr: string, en: string): Localized => ({ fr, en });
const ingredient = (
  fr: string,
  en: string,
  quantity: string,
  role: DishIngredient["role"],
  optional = false
): DishIngredient => ({ name: l(fr, en), quantity, role, optional });

export const DISH_LIBRARY: CulinaryDish[] = [
  {
    slug: "garba-ivoirien",
    name: l("Garba ivoirien", "Ivorian garba"),
    aliases: ["garba", "attiéké thon", "attieke tuna"],
    country: "Côte d'Ivoire",
    region: "Abidjan",
    category: "street-food",
    difficulty: "easy",
    timeMinutes: 25,
    servings: 4,
    featured: true,
    description: l("Attiéké servi avec du thon frit, des oignons, de la tomate et du piment frais.", "Attieke served with fried tuna, onions, tomato and fresh chili."),
    tradition: l("Plat populaire des garbadromes d'Abidjan, apprécié pour sa simplicité et sa générosité.", "A popular dish from Abidjan's garbadromes, loved for its simplicity and generous portions."),
    service: l("Servir aussitôt, avec l'huile de friture assaisonnée et le piment à part.", "Serve immediately with seasoned frying oil and chili on the side."),
    allergens: [l("Poisson", "Fish")],
    tags: ["ivoirien", "rapide", "poisson", "street food"],
    productKeywords: ["attieke", "thon", "poisson", "piment", "oignon", "tomate"],
    ingredients: [
      ingredient("Attiéké", "Attieke", "600 g", "base"),
      ingredient("Thon frais en morceaux", "Fresh tuna pieces", "600 g", "protein"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Tomates", "Tomatoes", "3", "vegetable"),
      ingredient("Piment frais", "Fresh chili", "selon goût", "spice", true),
      ingredient("Huile de friture", "Frying oil", "50 cl", "fat"),
    ],
    steps: [
      l("Éponger le thon, retirer les arêtes visibles, puis saler toutes les faces. Couvrir et laisser reposer 10 minutes au frais afin que l'assaisonnement pénètre sans dessécher la chair.", "Pat the tuna dry, remove any visible bones, then salt every side. Cover and refrigerate for 10 minutes so the seasoning penetrates without drying the flesh."),
      l("Chauffer l'huile à feu vif dans une casserole profonde. Frire le thon en petites quantités 4 à 6 minutes par face, sans surcharger, jusqu'à obtenir une croûte dorée et une chair opaque qui se détache facilement.", "Heat the oil over high heat in a deep pan. Fry the tuna in small batches for 4 to 6 minutes per side, without crowding, until golden outside and opaque and flaky inside."),
      l("Déposer le thon sur une grille ou du papier absorbant pendant 2 minutes. Conserver séparément une petite quantité d'huile de friture limpide pour assaisonner l'attiéké au moment du service.", "Drain the tuna on a rack or absorbent paper for 2 minutes. Keep a small amount of clear frying oil separately to season the attieke when serving."),
      l("Humidifier légèrement l'attiéké, puis le réchauffer à la vapeur 5 à 7 minutes à feu moyen. L'égrener à la fourchette jusqu'à ce que les grains soient chauds, souples et parfaitement séparés.", "Lightly moisten the attieke, then steam it over medium heat for 5 to 7 minutes. Fluff with a fork until the grains are hot, supple and completely separated."),
      l("Émincer finement les oignons, couper les tomates en petits dés et hacher le piment à part. Assaisonner la garniture d'une pincée de sel juste avant de dresser pour qu'elle reste croquante.", "Thinly slice the onions, dice the tomatoes and chop the chili separately. Season the garnish with a pinch of salt just before plating so it stays crisp."),
      l("Répartir l'attiéké chaud, ajouter un filet d'huile réservée, puis poser le thon et la garniture fraîche. Servir immédiatement avec le piment à part afin que chacun règle l'intensité.", "Divide the hot attieke, add a little reserved oil, then top with the tuna and fresh garnish. Serve immediately with chili on the side so everyone can adjust the heat."),
    ],
  },
  {
    slug: "kedjenou-de-poulet",
    name: l("Kédjénou de poulet", "Chicken kedjenou"),
    aliases: ["kedjenou", "kédjénou", "poulet kedjenou"],
    country: "Côte d'Ivoire",
    region: "Centre baoulé",
    category: "main",
    difficulty: "medium",
    timeMinutes: 70,
    servings: 6,
    featured: true,
    description: l("Poulet fermier mijoté à l'étouffée avec tomate, oignon, aubergine et aromates, sans ajout d'eau.", "Free-range chicken slowly steamed with tomato, onion, eggplant and aromatics, without added water."),
    tradition: l("La cuisson fermée concentre le jus naturel du poulet et des légumes ; la cocotte n'est ouverte qu'en fin de cuisson.", "The sealed cooking method concentrates the natural juices of the chicken and vegetables; the pot is opened only near the end."),
    service: l("Accompagner d'attiéké, de riz ou de foutou banane.", "Serve with attieke, rice or plantain foutou."),
    allergens: [],
    tags: ["ivoirien", "mijoté", "poulet", "sans gluten"],
    productKeywords: ["poulet", "aubergine", "tomate", "oignon", "gingembre", "attiéké"],
    ingredients: [
      ingredient("Poulet fermier découpé", "Cut free-range chicken", "1,5 kg", "protein"),
      ingredient("Tomates mûres", "Ripe tomatoes", "5", "vegetable"),
      ingredient("Oignons", "Onions", "3", "vegetable"),
      ingredient("Aubergines africaines", "African eggplants", "4", "vegetable"),
      ingredient("Gingembre et ail", "Ginger and garlic", "2 c. à soupe", "spice"),
      ingredient("Piment frais", "Fresh chili", "1", "spice", true),
      ingredient("Thym et laurier", "Thyme and bay leaf", "1 bouquet", "spice"),
    ],
    steps: [
      l("Éponger les morceaux de poulet, puis les masser avec le sel, l'ail et le gingembre. Couvrir et laisser reposer 15 minutes au frais pendant la préparation des légumes.", "Pat the chicken pieces dry, then rub them with salt, garlic and ginger. Cover and refrigerate for 15 minutes while preparing the vegetables."),
      l("Couper tomates, oignons et aubergines en morceaux réguliers de 2 à 3 cm. Cette taille permet aux légumes de rendre leur jus au même rythme sans disparaître dans la sauce.", "Cut the tomatoes, onions and eggplants into even 2 to 3 cm pieces. This size lets the vegetables release their juices evenly without vanishing into the sauce."),
      l("Déposer le poulet au fond d'une cocotte épaisse, puis répartir légumes, thym, laurier et piment par-dessus. Ne pas ajouter d'eau : le jus naturel doit assurer la cuisson à l'étouffée.", "Place the chicken in the bottom of a heavy pot, then spread the vegetables, thyme, bay leaf and chili on top. Do not add water: the natural juices should steam the dish."),
      l("Fermer hermétiquement la cocotte et cuire 15 minutes à feu moyen, sans ouvrir. De la vapeur doit se former et un léger frémissement doit être audible, sans bouillonnement violent.", "Seal the pot and cook over medium heat for 15 minutes without opening. Steam should build and a gentle simmer should be audible, never a hard boil."),
      l("Passer à feu doux et poursuivre 35 à 40 minutes. Toutes les 10 minutes, saisir les poignées avec protection et secouer doucement la cocotte pour répartir le jus sans casser les légumes.", "Reduce to low heat and cook for another 35 to 40 minutes. Every 10 minutes, hold the protected handles and gently shake the pot to redistribute the juices without breaking the vegetables."),
      l("Couper le feu, attendre 2 minutes, puis ouvrir en dirigeant la vapeur loin du visage. Vérifier que le poulet est cuit uniformément près de l'os et que les aubergines sont fondantes.", "Turn off the heat, wait 2 minutes, then open with the steam directed away from your face. Check that the chicken is evenly cooked near the bone and the eggplants are tender."),
      l("Si le jus est trop abondant, retirer le poulet et réduire la sauce 5 à 8 minutes à feu moyen. Remettre le poulet, goûter, rectifier le sel, puis servir après 5 minutes de repos.", "If there is too much liquid, remove the chicken and reduce the sauce over medium heat for 5 to 8 minutes. Return the chicken, taste, adjust the salt and serve after resting for 5 minutes."),
    ],
  },
  {
    slug: "attieke-poisson-braise",
    name: l("Attiéké au poisson braisé", "Attieke with grilled fish"),
    aliases: ["attiéké poisson", "attieke poisson", "atchéké poisson"],
    country: "Côte d'Ivoire",
    region: "Littoral ivoirien",
    category: "grill",
    difficulty: "medium",
    timeMinutes: 50,
    servings: 4,
    featured: true,
    description: l("Semoule de manioc légèrement acidulée, poisson mariné et braisé, crudités et sauce pimentée.", "Lightly tangy cassava couscous with marinated grilled fish, raw vegetables and chili sauce."),
    tradition: l("Un incontournable des maquis ivoiriens, servi en portions généreuses et partagé à table.", "A staple of Ivorian maquis restaurants, served generously and shared at the table."),
    service: l("Ajouter une salade d'oignons et tomates citronnée juste avant de servir.", "Add a lemony onion and tomato salad just before serving."),
    allergens: [l("Poisson", "Fish")],
    tags: ["ivoirien", "braisé", "poisson", "manioc"],
    productKeywords: ["attieke", "tilapia", "capitaine", "poisson", "piment", "citron"],
    ingredients: [
      ingredient("Attiéké", "Attieke", "700 g", "base"),
      ingredient("Tilapia ou capitaine entier", "Whole tilapia or captain fish", "1,2 kg", "protein"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Tomates", "Tomatoes", "3", "vegetable"),
      ingredient("Citron", "Lemon", "2", "spice"),
      ingredient("Ail et gingembre", "Garlic and ginger", "2 c. à soupe", "spice"),
      ingredient("Piment frais", "Fresh chili", "selon goût", "spice", true),
    ],
    steps: [
      l("Rincer rapidement le poisson nettoyé, l'éponger et pratiquer 3 à 4 incisions peu profondes de chaque côté. Mélanger citron, ail, gingembre et sel, puis masser la marinade jusque dans les entailles.", "Briefly rinse the cleaned fish, pat it dry and make 3 to 4 shallow cuts on each side. Mix lemon, garlic, ginger and salt, then rub the marinade into the cuts."),
      l("Couvrir le poisson et le laisser mariner 20 minutes au frais. Pendant ce temps, préchauffer le gril à feu moyen-vif et huiler légèrement la grille pour limiter l'adhérence.", "Cover and refrigerate the fish for 20 minutes. Meanwhile, preheat the grill over medium-high heat and lightly oil the grate to reduce sticking."),
      l("Égoutter le poisson et retirer l'excès de marinade humide. Le déposer sur le gril chaud et cuire 8 à 12 minutes par face selon l'épaisseur, sans le déplacer durant les premières minutes.", "Drain the fish and remove excess wet marinade. Place it on the hot grill and cook for 8 to 12 minutes per side depending on thickness, without moving it during the first few minutes."),
      l("Retourner le poisson une seule fois avec une spatule large. Il est prêt lorsque la peau est bien colorée, que la chair est opaque et qu'elle se détache facilement près de l'arête centrale.", "Turn the fish only once with a wide spatula. It is ready when the skin is well coloured and the flesh is opaque and flakes easily near the centre bone."),
      l("Humidifier légèrement l'attiéké et le cuire à la vapeur 5 à 7 minutes à feu moyen. Ajouter un filet d'huile, puis l'égrener à la fourchette pour obtenir des grains souples et séparés.", "Lightly moisten the attieke and steam it over medium heat for 5 to 7 minutes. Add a little oil, then fluff with a fork until the grains are supple and separate."),
      l("Émincer l'oignon, couper la tomate en dés et ajouter citron, sel et piment progressivement. Mélanger juste avant le service afin de conserver une garniture fraîche et croquante.", "Thinly slice the onion, dice the tomato and gradually add lemon, salt and chili. Mix just before serving to keep the garnish fresh and crisp."),
      l("Dresser l'attiéké chaud, poser le poisson braisé entier et répartir la garniture à côté plutôt que sur la peau. Servir le reste de citron et le piment séparément.", "Plate the hot attieke, add the whole grilled fish and place the garnish beside it rather than on the skin. Serve the remaining lemon and chili separately."),
    ],
  },
  {
    slug: "foutou-banane-sauce-graine",
    name: l("Foutou banane sauce graine", "Plantain foutou with palm nut sauce"),
    aliases: ["foutou sauce graine", "foutou banane", "plantain foutou"],
    country: "Côte d'Ivoire",
    region: "Sud et Centre",
    category: "main",
    difficulty: "hard",
    timeMinutes: 105,
    servings: 6,
    featured: true,
    description: l("Pâte pilée de banane plantain et manioc accompagnée d'une sauce riche aux noix de palme.", "Pounded plantain and cassava dough served with a rich palm nut sauce."),
    tradition: l("Plat de réception et de repas familial, le foutou demande une texture lisse, souple et homogène.", "A celebration and family dish, foutou should be smooth, supple and even."),
    service: l("Former des boules de foutou et servir la sauce graine séparément avec viande ou poisson fumé.", "Shape the foutou into balls and serve the palm sauce separately with meat or smoked fish."),
    allergens: [l("Poisson si ajouté", "Fish if used")],
    tags: ["ivoirien", "foutou", "sauce graine", "repas familial"],
    productKeywords: ["plantain", "manioc", "graine de palme", "huile de palme", "kplo", "poisson fumé"],
    ingredients: [
      ingredient("Bananes plantain mûres", "Ripe plantains", "6", "base"),
      ingredient("Manioc frais", "Fresh cassava", "500 g", "base"),
      ingredient("Concentré de noix de palme", "Palm nut concentrate", "800 g", "base"),
      ingredient("Viande de bœuf", "Beef", "600 g", "protein"),
      ingredient("Poisson fumé", "Smoked fish", "250 g", "protein", true),
      ingredient("Oignon et tomate", "Onion and tomato", "3 et 3", "vegetable"),
      ingredient("Piment frais", "Fresh chili", "1", "spice", true),
    ],
    steps: [
      l("Éplucher plantains et manioc, retirer la fibre centrale du manioc et couper le tout en morceaux réguliers. Rincer, couvrir d'eau froide et porter à ébullition à feu moyen.", "Peel the plantains and cassava, remove the cassava's central fibre and cut everything into even pieces. Rinse, cover with cold water and bring to the boil over medium heat."),
      l("Cuire 20 à 30 minutes, jusqu'à ce que la pointe d'un couteau traverse plantain et manioc sans résistance. Égoutter en réservant une tasse d'eau de cuisson et maintenir les morceaux bien chauds.", "Cook for 20 to 30 minutes, until a knife slides through the plantain and cassava without resistance. Drain, reserving one cup of cooking water, and keep the pieces hot."),
      l("Piler d'abord le manioc chaud jusqu'à disparition des fibres, puis incorporer le plantain par petites quantités. Humidifier légèrement le pilon si nécessaire et travailler jusqu'à obtenir une pâte lisse, souple et sans grumeaux.", "Pound the hot cassava first until the fibres disappear, then add the plantain a little at a time. Lightly wet the pestle if needed and work until the dough is smooth, supple and free of lumps."),
      l("Diluer le concentré de noix de palme avec de l'eau tiède selon son conditionnement, puis filtrer si nécessaire. Porter à frémissement 10 minutes à feu moyen en remuant pour obtenir une base homogène.", "Loosen the palm nut concentrate with warm water according to its packaging, then strain if needed. Simmer over medium heat for 10 minutes, stirring until the base is even."),
      l("Ajouter la viande, les oignons et les tomates. Couvrir partiellement et mijoter 40 à 45 minutes à feu doux, en remuant le fond toutes les 10 minutes, jusqu'à ce que la viande soit tendre et l'huile légèrement visible en surface.", "Add the meat, onions and tomatoes. Partially cover and simmer over low heat for 40 to 45 minutes, scraping the base every 10 minutes, until the meat is tender and a little oil shows on the surface."),
      l("Ajouter le poisson fumé et le piment entier pour les 10 dernières minutes, sans trop remuer afin de préserver les morceaux. Goûter et ajuster le sel ainsi que la consistance avec un peu d'eau réservée.", "Add the smoked fish and whole chili for the final 10 minutes, stirring very little to preserve the pieces. Taste and adjust the salt and consistency with a little reserved water."),
      l("Avec les mains légèrement humidifiées, diviser le foutou chaud et former des boules lisses. Couvrir pour éviter qu'elles ne croûtent pendant la finition de la sauce.", "With lightly moistened hands, divide the hot foutou and shape it into smooth balls. Cover to prevent a skin forming while the sauce is finished."),
      l("Laisser la sauce reposer 5 minutes hors du feu, retirer le piment si nécessaire, puis servir très chaud dans un plat séparé. Le foutou doit rester souple et la sauce nappante.", "Rest the sauce off the heat for 5 minutes, remove the chili if needed, then serve very hot in a separate dish. The foutou should remain supple and the sauce should lightly coat a spoon."),
    ],
  },
  {
    slug: "placali-sauce-gombo",
    name: l("Placali sauce gombo", "Placali with okra sauce"),
    aliases: ["placali gombo", "placali sauce kopè", "cassava dough okra"],
    country: "Côte d'Ivoire",
    region: "Sud ivoirien",
    category: "main",
    difficulty: "medium",
    timeMinutes: 65,
    servings: 6,
    featured: true,
    description: l("Pâte souple de manioc fermenté servie avec une sauce gombo filante au poisson fumé.", "Soft fermented cassava dough served with silky okra sauce and smoked fish."),
    tradition: l("Le placali se travaille chaud jusqu'à devenir brillant et sans grumeaux.", "Placali is worked while hot until glossy and completely smooth."),
    service: l("Servir dans des bols séparés, avec piment frais pour les amateurs.", "Serve in separate bowls with fresh chili on the side."),
    allergens: [l("Poisson", "Fish"), l("Crustacés selon la recette", "Shellfish depending on recipe")],
    tags: ["ivoirien", "manioc", "gombo", "poisson fumé"],
    productKeywords: ["placali", "manioc", "gombo", "djoumble", "poisson fumé", "kplo"],
    ingredients: [
      ingredient("Pâte de placali", "Placali dough", "1,2 kg", "base"),
      ingredient("Gombo frais", "Fresh okra", "600 g", "vegetable"),
      ingredient("Djoumblé en poudre", "Dried okra powder", "2 c. à soupe", "spice", true),
      ingredient("Poisson fumé", "Smoked fish", "350 g", "protein"),
      ingredient("Crabes", "Crabs", "4", "protein", true),
      ingredient("Huile de palme", "Palm oil", "3 c. à soupe", "fat"),
      ingredient("Piment", "Chili", "selon goût", "spice", true),
    ],
    steps: [
      l("Placer la pâte de placali dans une casserole épaisse et ajouter progressivement de l'eau froide en fouettant. Continuer jusqu'à obtenir un liquide lisse, sans poche de pâte ni grumeau.", "Place the placali dough in a heavy pan and gradually whisk in cold water. Continue until the mixture is smooth, with no pockets of dough or lumps."),
      l("Cuire à feu moyen 12 à 15 minutes en remuant sans interruption avec une spatule solide. Racler le fond et les parois jusqu'à ce que la pâte épaississe, devienne translucide et se détache légèrement de la casserole.", "Cook over medium heat for 12 to 15 minutes, stirring constantly with a sturdy spatula. Scrape the base and sides until the dough thickens, turns translucent and pulls slightly from the pan."),
      l("Baisser le feu, travailler encore 3 à 5 minutes pour lisser la texture, puis couvrir et garder au chaud. Le placali final doit être brillant, souple et sans grumeaux visibles.", "Lower the heat, work the dough for another 3 to 5 minutes to smooth it, then cover and keep warm. The finished placali should be glossy, supple and free of visible lumps."),
      l("Émincer très finement le gombo pour développer sa texture filante. Le placer dans une seconde casserole avec un petit fond d'eau et cuire 8 minutes à feu moyen en remuant doucement.", "Slice the okra very finely to develop its silky texture. Place it in a second pan with a small amount of water and cook over medium heat for 8 minutes, stirring gently."),
      l("Ajouter l'huile de palme, le poisson fumé, les crabes et l'assaisonnement. Couvrir partiellement et laisser frémir 18 à 20 minutes à feu doux sans casser les morceaux de poisson.", "Add the palm oil, smoked fish, crabs and seasoning. Partially cover and gently simmer over low heat for 18 to 20 minutes without breaking the fish pieces."),
      l("Saupoudrer le djoumblé en pluie si désiré, puis remuer 2 à 3 minutes pour éviter les amas. Ajuster avec un peu d'eau chaude jusqu'à obtenir une sauce homogène, brillante et filante.", "Sprinkle in the dried okra powder if using, then stir for 2 to 3 minutes to prevent clumps. Adjust with a little hot water until the sauce is even, glossy and silky."),
      l("Goûter, régler le sel et proposer le piment séparément. Servir immédiatement le placali et la sauce dans deux plats chauds afin que chacun compose sa portion.", "Taste, adjust the salt and offer chili separately. Serve the placali and sauce immediately in two warm dishes so everyone can assemble their own portion."),
    ],
  },
  {
    slug: "alloco-poulet-braise",
    name: l("Alloco et poulet braisé", "Alloco with grilled chicken"),
    aliases: ["alloco poulet", "plantain poulet", "fried plantain chicken"],
    country: "Côte d'Ivoire",
    region: "Abidjan",
    category: "street-food",
    difficulty: "easy",
    timeMinutes: 45,
    servings: 4,
    description: l("Bananes plantain mûres frites et poulet mariné puis braisé, avec sauce tomate pimentée.", "Fried ripe plantains with marinated grilled chicken and spicy tomato sauce."),
    tradition: l("Un duo emblématique des allocodromes et des soirées ivoiriennes.", "An iconic pairing from Ivorian allocodromes and evening gatherings."),
    service: l("Égoutter soigneusement l'alloco et servir sans attendre pour préserver ses bords caramélisés.", "Drain the alloco well and serve immediately to keep its caramelized edges."),
    allergens: [],
    tags: ["ivoirien", "plantain", "braisé", "convivial"],
    productKeywords: ["banane plantain", "poulet", "piment", "tomate", "huile"],
    ingredients: [
      ingredient("Bananes plantain très mûres", "Very ripe plantains", "6", "base"),
      ingredient("Poulet découpé", "Cut chicken", "1,2 kg", "protein"),
      ingredient("Ail et gingembre", "Garlic and ginger", "2 c. à soupe", "spice"),
      ingredient("Tomates", "Tomatoes", "4", "vegetable"),
      ingredient("Oignon", "Onion", "1", "vegetable"),
      ingredient("Huile de friture", "Frying oil", "50 cl", "fat"),
      ingredient("Piment", "Chili", "selon goût", "spice", true),
    ],
    steps: [
      l("Éponger le poulet, puis mélanger ail, gingembre, sel et épices avec un filet d'huile. Masser chaque morceau, couvrir et laisser mariner 30 minutes au frais.", "Pat the chicken dry, then mix garlic, ginger, salt and spices with a little oil. Rub every piece, cover and refrigerate for 30 minutes."),
      l("Préchauffer le gril à feu moyen-vif et huiler légèrement la grille. Égoutter le poulet, puis le braiser 25 à 35 minutes en le retournant toutes les 6 à 8 minutes pour obtenir une peau dorée sans brûler la marinade.", "Preheat the grill over medium-high heat and lightly oil the grate. Drain the chicken, then grill for 25 to 35 minutes, turning every 6 to 8 minutes for golden skin without burning the marinade."),
      l("Vérifier que la cuisson est homogène près de l'os, puis laisser reposer le poulet 5 minutes sous une feuille posée sans serrer. Ce repos conserve les jus dans la chair.", "Check that the chicken is evenly cooked near the bone, then rest it for 5 minutes under a loosely placed sheet. This keeps the juices in the meat."),
      l("Choisir des plantains très mûrs à peau largement noire. Les éplucher, les couper en biais en tranches régulières de 1,5 cm et les saler très légèrement juste avant la friture.", "Choose very ripe plantains with mostly black skins. Peel and cut diagonally into even 1.5 cm slices, then salt very lightly just before frying."),
      l("Chauffer l'huile à feu vif, puis frire les plantains en petites quantités 3 à 4 minutes par face. Les retirer lorsqu'ils sont dorés et caramélisés sur les bords, encore fondants au centre.", "Heat the oil over high heat, then fry the plantains in small batches for 3 to 4 minutes per side. Remove when golden and caramelised at the edges, while still soft in the centre."),
      l("Faire revenir oignon et tomate 8 à 10 minutes à feu moyen, jusqu'à obtenir une sauce courte et brillante. Ajouter le piment progressivement, goûter et ajuster le sel.", "Cook the onion and tomato over medium heat for 8 to 10 minutes, until the sauce is reduced and glossy. Add the chili gradually, taste and adjust the salt."),
      l("Égoutter l'alloco sur une grille ou du papier absorbant, puis dresser sans attendre avec le poulet reposé et la sauce chaude à côté. Ne pas napper l'alloco afin de préserver ses bords caramélisés.", "Drain the alloco on a rack or absorbent paper, then serve immediately with the rested chicken and hot sauce on the side. Do not cover the alloco with sauce, so its caramelised edges stay intact."),
    ],
  },
  {
    slug: "sauce-claire-poisson",
    name: l("Sauce claire au poisson", "Ivorian clear fish sauce"),
    aliases: ["sauce claire", "soupe poisson ivoirienne"],
    country: "Côte d'Ivoire",
    region: "Sud et littoral",
    category: "sauce",
    difficulty: "medium",
    timeMinutes: 60,
    servings: 6,
    description: l("Bouillon parfumé de poisson frais, tomate, aubergine africaine, gombo et piment entier.", "Fragrant broth of fresh fish, tomato, African eggplant, okra and whole chili."),
    tradition: l("Une sauce légère en apparence mais profonde en goût, souvent associée au foutou.", "A sauce that looks light yet tastes deeply savory, often paired with foutou."),
    service: l("Servir très chaud avec foutou igname, foutou banane ou riz blanc.", "Serve very hot with yam foutou, plantain foutou or white rice."),
    allergens: [l("Poisson", "Fish")],
    tags: ["ivoirien", "bouillon", "poisson", "foutou"],
    productKeywords: ["poisson", "capitaine", "aubergine", "gombo", "piment", "foutou"],
    ingredients: [
      ingredient("Poisson capitaine en darnes", "Captain fish steaks", "1 kg", "protein"),
      ingredient("Tomates", "Tomatoes", "5", "vegetable"),
      ingredient("Aubergines africaines", "African eggplants", "4", "vegetable"),
      ingredient("Gombos", "Okra", "8", "vegetable"),
      ingredient("Oignon", "Onion", "1", "vegetable"),
      ingredient("Piment entier", "Whole chili", "1", "spice", true),
    ],
    steps: [
      l("Assaisonner le poisson et le réserver au frais.", "Season the fish and keep it chilled."),
      l("Cuire tomates, oignon et aubergines dans l'eau pendant 20 minutes.", "Cook tomatoes, onion and eggplants in water for 20 minutes."),
      l("Mixer les légumes cuits puis remettre la purée dans le bouillon.", "Blend the cooked vegetables and return the puree to the broth."),
      l("Ajouter gombos, piment entier et poisson sans trop remuer.", "Add okra, whole chili and fish without stirring too much."),
      l("Laisser frémir 15 à 20 minutes et rectifier l'assaisonnement.", "Simmer for 15 to 20 minutes and adjust seasoning."),
    ],
  },
  {
    slug: "biekosseu",
    name: l("Biékosseu", "Biekosseu"),
    aliases: ["biékosseu", "biekosseu", "sauce piment poisson"],
    country: "Côte d'Ivoire",
    region: "Pays attié",
    category: "sauce",
    difficulty: "medium",
    timeMinutes: 55,
    servings: 5,
    description: l("Poisson cuit dans une sauce relevée au piment, à la tomate et aux aromates, traditionnellement en papillote ou à l'étouffée.", "Fish cooked in a bold chili, tomato and aromatic sauce, traditionally wrapped or steamed."),
    tradition: l("Spécialité attié dont le nom et la composition varient légèrement selon les familles.", "An Attie specialty whose name and composition vary slightly from one family to another."),
    service: l("Accompagner d'attiéké ou de banane plantain bouillie.", "Serve with attieke or boiled plantain."),
    allergens: [l("Poisson", "Fish")],
    tags: ["ivoirien", "attié", "poisson", "pimenté"],
    productKeywords: ["poisson", "piment", "tomate", "attiéké", "plantain"],
    ingredients: [
      ingredient("Poisson entier nettoyé", "Cleaned whole fish", "1 kg", "protein"),
      ingredient("Piments frais", "Fresh chilies", "4", "spice"),
      ingredient("Tomates", "Tomatoes", "4", "vegetable"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Ail", "Garlic", "3 gousses", "spice"),
      ingredient("Huile", "Oil", "3 c. à soupe", "fat"),
    ],
    steps: [
      l("Piler ou mixer piment, tomate, oignon et ail.", "Pound or blend chili, tomato, onion and garlic."),
      l("Assaisonner le poisson et l'enduire d'une partie de la sauce.", "Season the fish and coat it with part of the sauce."),
      l("Déposer le poisson dans une cocotte ou une papillote résistante.", "Place the fish in a pot or sturdy wrapping."),
      l("Ajouter le reste de sauce et cuire à l'étouffée 30 à 35 minutes.", "Add the remaining sauce and steam for 30 to 35 minutes."),
      l("Vérifier la cuisson à cœur et servir avec la sauce concentrée.", "Check that the fish is cooked through and serve with the concentrated sauce."),
    ],
  },
  {
    slug: "gouagouassou-boeuf",
    name: l("Gouagouassou de bœuf", "Beef gouagouassou"),
    aliases: ["gouagouassou", "sauce gouagouassou"],
    country: "Côte d'Ivoire",
    region: "Centre ivoirien",
    category: "sauce",
    difficulty: "medium",
    timeMinutes: 85,
    servings: 6,
    description: l("Sauce ivoirienne généreuse à la viande, tomate, aubergine et gombo, mijotée jusqu'à tendreté.", "Generous Ivorian beef sauce with tomato, eggplant and okra, simmered until tender."),
    tradition: l("Plat familial souvent servi avec foutou ou riz, apprécié pour son bouillon dense.", "A family dish often served with foutou or rice and prized for its full-bodied broth."),
    service: l("Laisser reposer cinq minutes avant de servir afin que la sauce se stabilise.", "Rest for five minutes before serving so the sauce settles."),
    allergens: [],
    tags: ["ivoirien", "bœuf", "mijoté", "sauce"],
    productKeywords: ["boeuf", "viande", "aubergine", "gombo", "tomate", "foutou"],
    ingredients: [
      ingredient("Bœuf à mijoter", "Stewing beef", "900 g", "protein"),
      ingredient("Tomates", "Tomatoes", "5", "vegetable"),
      ingredient("Aubergines africaines", "African eggplants", "5", "vegetable"),
      ingredient("Gombos", "Okra", "10", "vegetable"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Piment", "Chili", "1", "spice", true),
    ],
    steps: [
      l("Faire revenir le bœuf assaisonné jusqu'à légère coloration.", "Brown the seasoned beef lightly."),
      l("Ajouter oignon et tomate, puis laisser compoter dix minutes.", "Add onion and tomato, then cook down for ten minutes."),
      l("Couvrir d'eau et mijoter 40 minutes à feu doux.", "Cover with water and simmer over low heat for 40 minutes."),
      l("Ajouter aubergines et gombos, puis poursuivre la cuisson 20 minutes.", "Add eggplants and okra, then cook for another 20 minutes."),
      l("Écraser quelques légumes dans le bouillon pour lier naturellement la sauce.", "Mash a few vegetables into the broth to thicken the sauce naturally."),
    ],
  },
  {
    slug: "riz-gras-ivoirien",
    name: l("Riz gras ivoirien", "Ivorian tomato rice"),
    aliases: ["riz gras", "riz rouge ivoirien"],
    country: "Côte d'Ivoire",
    region: "National",
    category: "main",
    difficulty: "easy",
    timeMinutes: 55,
    servings: 6,
    description: l("Riz cuit dans une base tomate assaisonnée, garni de légumes et de viande ou de poulet.", "Rice cooked in a seasoned tomato base with vegetables and beef or chicken."),
    tradition: l("Un plat complet des grandes tablées, facile à adapter aux produits disponibles.", "A complete dish for large tables, easy to adapt to available ingredients."),
    service: l("Servir avec une salade fraîche et du piment à part.", "Serve with a fresh salad and chili on the side."),
    allergens: [],
    tags: ["ivoirien", "riz", "familial", "complet"],
    productKeywords: ["riz", "tomate", "poulet", "boeuf", "carotte", "piment"],
    ingredients: [
      ingredient("Riz long grain", "Long-grain rice", "600 g", "base"),
      ingredient("Poulet ou bœuf", "Chicken or beef", "700 g", "protein"),
      ingredient("Concentré de tomate", "Tomato paste", "150 g", "vegetable"),
      ingredient("Carottes", "Carrots", "3", "vegetable"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Huile", "Oil", "6 c. à soupe", "fat"),
      ingredient("Ail, laurier et thym", "Garlic, bay leaf and thyme", "selon goût", "spice"),
    ],
    steps: [
      l("Dorer la viande dans l'huile puis la réserver.", "Brown the meat in oil, then set it aside."),
      l("Faire revenir oignons et concentré de tomate jusqu'à perdre l'acidité crue.", "Cook onions and tomato paste until the raw acidity is gone."),
      l("Ajouter viande, aromates, carottes et eau, puis cuire 15 minutes.", "Add meat, herbs, carrots and water, then cook for 15 minutes."),
      l("Rincer le riz et l'incorporer au bouillon en contrôlant le niveau de liquide.", "Rinse the rice and add it to the broth, checking the liquid level."),
      l("Cuire couvert à feu doux jusqu'à absorption, puis laisser reposer 10 minutes.", "Cook covered over low heat until absorbed, then rest for 10 minutes."),
    ],
  },
  {
    slug: "thieboudienne",
    name: l("Thiéboudiène", "Thieboudienne"),
    aliases: ["thiéboudienne", "ceebu jën", "riz au poisson sénégalais"],
    country: "Sénégal",
    region: "Saint-Louis et Dakar",
    category: "main",
    difficulty: "hard",
    timeMinutes: 120,
    servings: 8,
    featured: true,
    description: l("Riz cassé au poisson, cuit dans un bouillon tomaté avec légumes entiers et farce aromatique.", "Broken rice with fish cooked in a tomato broth with whole vegetables and aromatic stuffing."),
    tradition: l("Plat national sénégalais associé au partage ; chaque composant est cuit dans le même bouillon.", "Senegal's national dish, associated with sharing; every component cooks in the same broth."),
    service: l("Dresser le riz sur un grand plat et disposer poisson et légumes au centre.", "Spread the rice on a large platter and arrange fish and vegetables in the center."),
    allergens: [l("Poisson", "Fish")],
    tags: ["sénégalais", "riz", "poisson", "plat national"],
    productKeywords: ["riz", "poisson", "concentre tomate", "manioc", "chou", "piment"],
    ingredients: [
      ingredient("Riz cassé", "Broken rice", "1 kg", "base"),
      ingredient("Poisson ferme entier", "Firm whole fish", "1,5 kg", "protein"),
      ingredient("Concentré de tomate", "Tomato paste", "200 g", "vegetable"),
      ingredient("Chou, carottes et manioc", "Cabbage, carrots and cassava", "1 assortiment", "vegetable"),
      ingredient("Persil, ail et piment", "Parsley, garlic and chili", "1 bouquet", "spice"),
      ingredient("Huile", "Oil", "15 cl", "fat"),
    ],
    steps: [
      l("Piler persil, ail, piment et sel, puis farcir les incisions du poisson.", "Pound parsley, garlic, chili and salt, then stuff the fish slits."),
      l("Frire légèrement le poisson et le réserver.", "Lightly fry the fish and set it aside."),
      l("Cuire le concentré de tomate dans l'huile puis ajouter eau et légumes.", "Cook the tomato paste in oil, then add water and vegetables."),
      l("Retirer les légumes cuits, remettre le poisson quelques minutes puis le réserver.", "Remove the cooked vegetables, return the fish briefly, then set it aside."),
      l("Cuire le riz rincé dans le bouillon filtré jusqu'à absorption.", "Cook the rinsed rice in the strained broth until absorbed."),
      l("Former une légère croûte de riz au fond si désiré, puis dresser le plat.", "Create a light rice crust at the bottom if desired, then assemble the platter."),
    ],
  },
  {
    slug: "yassa-poulet",
    name: l("Yassa poulet", "Chicken yassa"),
    aliases: ["poulet yassa", "yassa chicken"],
    country: "Sénégal",
    region: "Casamance",
    category: "main",
    difficulty: "medium",
    timeMinutes: 75,
    servings: 6,
    description: l("Poulet mariné au citron puis braisé, servi dans une sauce fondante aux oignons.", "Lemon-marinated grilled chicken served in a melting onion sauce."),
    tradition: l("La longue marinade et la cuisson lente des oignons donnent au yassa son équilibre acidulé et doux.", "A long marinade and slow-cooked onions give yassa its tangy, mellow balance."),
    service: l("Servir avec du riz blanc et conserver un peu de jus citronné pour la finition.", "Serve with white rice and reserve a little lemon juice for finishing."),
    allergens: [l("Moutarde selon la marinade", "Mustard depending on marinade")],
    tags: ["sénégalais", "poulet", "citron", "oignon"],
    productKeywords: ["poulet", "citron", "oignon", "moutarde", "riz"],
    ingredients: [
      ingredient("Poulet découpé", "Cut chicken", "1,5 kg", "protein"),
      ingredient("Oignons", "Onions", "1 kg", "vegetable"),
      ingredient("Citrons", "Lemons", "5", "spice"),
      ingredient("Moutarde", "Mustard", "2 c. à soupe", "spice", true),
      ingredient("Ail", "Garlic", "4 gousses", "spice"),
      ingredient("Huile", "Oil", "8 cl", "fat"),
    ],
    steps: [
      l("Mariner le poulet avec citron, ail, moutarde et une partie des oignons pendant au moins deux heures.", "Marinate the chicken with lemon, garlic, mustard and some onion for at least two hours."),
      l("Égoutter puis griller ou dorer le poulet.", "Drain, then grill or brown the chicken."),
      l("Faire fondre les oignons de la marinade à feu doux sans les brûler.", "Slowly soften the marinade onions without burning them."),
      l("Ajouter le jus de marinade et laisser réduire 10 minutes.", "Add the marinade liquid and reduce for 10 minutes."),
      l("Remettre le poulet dans la sauce et mijoter jusqu'à cuisson complète.", "Return the chicken to the sauce and simmer until cooked through."),
    ],
  },
  {
    slug: "mafe-boeuf",
    name: l("Mafé de bœuf", "Beef mafe"),
    aliases: ["mafé", "mafe", "sauce arachide"],
    country: "Mali / Sénégal",
    region: "Afrique de l'Ouest",
    category: "sauce",
    difficulty: "medium",
    timeMinutes: 80,
    servings: 6,
    description: l("Ragoût onctueux à la pâte d'arachide, tomate, viande et légumes.", "Creamy peanut stew with tomato, meat and vegetables."),
    tradition: l("Le mafé se retrouve dans plusieurs cuisines ouest-africaines, avec des équilibres variables entre arachide et tomate.", "Mafe appears across several West African cuisines, with varying balances of peanut and tomato."),
    service: l("Servir avec du riz blanc, en proposant le piment séparément.", "Serve with white rice and offer chili separately."),
    allergens: [l("Arachides", "Peanuts")],
    tags: ["ouest-africain", "arachide", "bœuf", "mijoté"],
    productKeywords: ["pate arachide", "arachide", "boeuf", "tomate", "riz", "piment"],
    ingredients: [
      ingredient("Bœuf à mijoter", "Stewing beef", "900 g", "protein"),
      ingredient("Pâte d'arachide non sucrée", "Unsweetened peanut paste", "300 g", "base"),
      ingredient("Concentré de tomate", "Tomato paste", "120 g", "vegetable"),
      ingredient("Carottes et patate douce", "Carrots and sweet potato", "600 g", "vegetable"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Piment", "Chili", "1", "spice", true),
    ],
    steps: [
      l("Dorer la viande puis ajouter oignons et concentré de tomate.", "Brown the meat, then add onions and tomato paste."),
      l("Mouiller à hauteur et mijoter 30 minutes.", "Cover with liquid and simmer for 30 minutes."),
      l("Délayer la pâte d'arachide dans du bouillon chaud avant de l'incorporer.", "Loosen the peanut paste with hot broth before adding it."),
      l("Ajouter les légumes et cuire à feu doux 30 minutes en remuant régulièrement.", "Add the vegetables and cook over low heat for 30 minutes, stirring regularly."),
      l("Ajuster la consistance avec un peu d'eau et vérifier l'assaisonnement.", "Adjust the consistency with a little water and check seasoning."),
    ],
  },
  {
    slug: "ndole-crevettes",
    name: l("Ndolé aux crevettes", "Ndole with prawns"),
    aliases: ["ndolé", "ndole", "feuilles amères"],
    country: "Cameroun",
    region: "Littoral",
    category: "main",
    difficulty: "hard",
    timeMinutes: 105,
    servings: 8,
    featured: true,
    description: l("Feuilles amères longuement préparées, liées à l'arachide et garnies de crevettes ou de viande.", "Carefully prepared bitter leaves bound with peanuts and topped with prawns or meat."),
    tradition: l("Plat de fête camerounais dont la réussite dépend du lavage des feuilles et d'une pâte d'arachide bien cuite.", "A Cameroonian celebration dish whose success depends on washing the leaves and thoroughly cooking the peanut paste."),
    service: l("Accompagner de plantain mûr, de miondo ou de bâton de manioc.", "Serve with ripe plantain, miondo or cassava sticks."),
    allergens: [l("Arachides", "Peanuts"), l("Crustacés", "Shellfish")],
    tags: ["camerounais", "feuilles", "arachide", "crevettes"],
    productKeywords: ["ndole", "feuilles amères", "arachide", "crevette", "plantain", "manioc"],
    ingredients: [
      ingredient("Feuilles de ndolé préparées", "Prepared bitter leaves", "800 g", "vegetable"),
      ingredient("Arachides blanches", "Blanched peanuts", "400 g", "base"),
      ingredient("Crevettes", "Prawns", "500 g", "protein"),
      ingredient("Bœuf", "Beef", "500 g", "protein", true),
      ingredient("Oignons", "Onions", "3", "vegetable"),
      ingredient("Huile", "Oil", "12 cl", "fat"),
    ],
    steps: [
      l("Laver et blanchir les feuilles jusqu'à obtenir une amertume équilibrée.", "Wash and blanch the leaves until their bitterness is balanced."),
      l("Cuire les arachides puis les mixer en pâte fine.", "Cook the peanuts and blend them into a smooth paste."),
      l("Cuire la viande si utilisée et conserver son bouillon.", "Cook the meat if using and reserve its broth."),
      l("Mijoter pâte d'arachide, oignons et bouillon jusqu'à disparition du goût cru.", "Simmer peanut paste, onions and broth until the raw taste disappears."),
      l("Incorporer les feuilles puis cuire 20 minutes à feu doux.", "Fold in the leaves and cook over low heat for 20 minutes."),
      l("Sauter les crevettes à part et les disposer sur le ndolé au service.", "Saute the prawns separately and arrange them on the ndole to serve."),
    ],
  },
  {
    slug: "poulet-dg",
    name: l("Poulet DG", "Poulet DG"),
    aliases: ["poulet directeur général", "chicken dg"],
    country: "Cameroun",
    region: "National",
    category: "main",
    difficulty: "medium",
    timeMinutes: 65,
    servings: 6,
    description: l("Poulet doré, plantains mûrs et légumes sautés réunis dans une sauce parfumée.", "Golden chicken, ripe plantains and sauteed vegetables brought together in a fragrant sauce."),
    tradition: l("Né comme plat de prestige, il est aujourd'hui un classique convivial camerounais.", "Once considered a prestige dish, it is now a convivial Cameroonian classic."),
    service: l("Assembler au dernier moment pour garder les plantains entiers et légèrement caramélisés.", "Assemble at the last moment to keep the plantains intact and lightly caramelized."),
    allergens: [],
    tags: ["camerounais", "poulet", "plantain", "festif"],
    productKeywords: ["poulet", "banane plantain", "carotte", "poivron", "gingembre"],
    ingredients: [
      ingredient("Poulet découpé", "Cut chicken", "1,4 kg", "protein"),
      ingredient("Plantains mûrs", "Ripe plantains", "5", "base"),
      ingredient("Carottes et poivrons", "Carrots and bell peppers", "500 g", "vegetable"),
      ingredient("Oignons", "Onions", "2", "vegetable"),
      ingredient("Ail et gingembre", "Garlic and ginger", "2 c. à soupe", "spice"),
      ingredient("Huile", "Oil", "20 cl", "fat"),
    ],
    steps: [
      l("Assaisonner le poulet puis le dorer sur toutes ses faces.", "Season the chicken and brown it on all sides."),
      l("Ajouter oignons, ail, gingembre et un peu d'eau, puis cuire à couvert.", "Add onions, garlic, ginger and a little water, then cover and cook."),
      l("Frire ou rôtir les plantains en morceaux jusqu'à coloration.", "Fry or roast the plantain pieces until golden."),
      l("Sauter rapidement carottes et poivrons afin de garder leur tenue.", "Quickly saute the carrots and peppers so they retain their shape."),
      l("Réunir poulet, légumes et plantains dans la sauce et laisser prendre cinq minutes.", "Combine chicken, vegetables and plantains in the sauce and cook together for five minutes."),
    ],
  },
  {
    slug: "jollof-rice",
    name: l("Jollof rice", "Jollof rice"),
    aliases: ["riz jollof", "benachin", "riz tomate ouest africain"],
    country: "Nigeria / Ghana",
    region: "Afrique de l'Ouest",
    category: "main",
    difficulty: "medium",
    timeMinutes: 65,
    servings: 8,
    featured: true,
    description: l("Riz parfumé cuit dans une sauce tomate-poivron épicée, souvent accompagné de poulet grillé.", "Fragrant rice cooked in a spiced tomato and pepper sauce, often served with grilled chicken."),
    tradition: l("Chaque pays et chaque famille défend son équilibre de tomate, piment, fumé et épices.", "Each country and family has its own balance of tomato, chili, smokiness and spices."),
    service: l("Laisser reposer le riz couvert dix minutes avant de l'égrener.", "Rest the rice covered for ten minutes before fluffing."),
    allergens: [],
    tags: ["ouest-africain", "riz", "tomate", "festif"],
    productKeywords: ["riz", "tomate", "poivron", "piment", "poulet", "épices"],
    ingredients: [
      ingredient("Riz long grain étuvé", "Parboiled long-grain rice", "800 g", "base"),
      ingredient("Tomates", "Tomatoes", "700 g", "vegetable"),
      ingredient("Poivrons rouges", "Red bell peppers", "3", "vegetable"),
      ingredient("Oignons", "Onions", "3", "vegetable"),
      ingredient("Piment", "Chili", "selon goût", "spice", true),
      ingredient("Bouillon et épices", "Stock and spices", "1 L", "spice"),
      ingredient("Huile", "Oil", "12 cl", "fat"),
    ],
    steps: [
      l("Mixer tomates, poivrons, piment et un oignon.", "Blend tomatoes, peppers, chili and one onion."),
      l("Faire revenir le reste d'oignon puis cuire la purée jusqu'à concentration.", "Saute the remaining onion, then cook the puree until concentrated."),
      l("Ajouter bouillon, laurier et épices, puis porter à frémissement.", "Add stock, bay leaf and spices, then bring to a simmer."),
      l("Incorporer le riz rincé, couvrir hermétiquement et cuire à feu très doux.", "Add the rinsed rice, cover tightly and cook over very low heat."),
      l("Vérifier l'absorption sans trop remuer, puis laisser reposer avant de servir.", "Check absorption without stirring too much, then rest before serving."),
    ],
  },
  {
    slug: "egusi-soup",
    name: l("Soupe egusi", "Egusi soup"),
    aliases: ["egusi soup", "sauce graines de melon"],
    country: "Nigeria",
    region: "Afrique de l'Ouest",
    category: "sauce",
    difficulty: "medium",
    timeMinutes: 80,
    servings: 8,
    description: l("Sauce épaisse aux graines de melon moulues, légumes-feuilles, huile de palme et protéines variées.", "Thick melon-seed stew with leafy greens, palm oil and assorted proteins."),
    tradition: l("Servie avec fufu, eba ou igname pilée, sa texture dépend de la façon d'incorporer l'egusi.", "Served with fufu, eba or pounded yam; its texture depends on how the egusi is incorporated."),
    service: l("Servir chaude avec une pâte neutre qui recueille la sauce.", "Serve hot with a neutral swallow that carries the sauce."),
    allergens: [l("Graines de melon", "Melon seeds"), l("Poisson ou crustacés selon la recette", "Fish or shellfish depending on recipe")],
    tags: ["nigérian", "egusi", "huile de palme", "fufu"],
    productKeywords: ["egusi", "graines melon", "huile palme", "poisson fumé", "feuilles", "fufu"],
    ingredients: [
      ingredient("Egusi moulu", "Ground egusi", "400 g", "base"),
      ingredient("Bœuf ou chèvre", "Beef or goat", "700 g", "protein"),
      ingredient("Poisson fumé", "Smoked fish", "200 g", "protein", true),
      ingredient("Épinards ou feuilles vertes", "Spinach or leafy greens", "500 g", "vegetable"),
      ingredient("Huile de palme", "Palm oil", "15 cl", "fat"),
      ingredient("Piment et oignon", "Chili and onion", "selon goût", "spice"),
    ],
    steps: [
      l("Cuire la viande dans un bouillon assaisonné jusqu'à tendreté.", "Cook the meat in seasoned stock until tender."),
      l("Faire revenir oignon et piment dans l'huile de palme.", "Saute onion and chili in palm oil."),
      l("Mélanger l'egusi avec un peu d'eau puis l'ajouter par petites portions.", "Mix egusi with a little water and add it in small portions."),
      l("Laisser prendre sans trop remuer, puis ajouter viande, bouillon et poisson fumé.", "Let it set without over-stirring, then add meat, stock and smoked fish."),
      l("Terminer par les feuilles vertes et cuire encore dix minutes.", "Finish with the leafy greens and cook for ten more minutes."),
    ],
  },
  {
    slug: "waakye",
    name: l("Waakye", "Waakye"),
    aliases: ["riz haricots ghanéen", "waache"],
    country: "Ghana",
    region: "National",
    category: "street-food",
    difficulty: "medium",
    timeMinutes: 75,
    servings: 8,
    description: l("Riz et haricots cornille cuits ensemble, servis avec sauce tomate, protéines et garnitures variées.", "Rice and black-eyed peas cooked together and served with tomato stew, proteins and assorted toppings."),
    tradition: l("Petit-déjeuner et déjeuner populaire ghanéen, le waakye se distingue par la diversité de ses accompagnements.", "A popular Ghanaian breakfast and lunch, waakye stands out for its wide range of accompaniments."),
    service: l("Présenter les garnitures séparément afin que chacun compose son assiette.", "Present the toppings separately so everyone can build their own plate."),
    allergens: [l("Poisson selon la garniture", "Fish depending on topping"), l("Gluten si spaghetti", "Gluten if served with spaghetti")],
    tags: ["ghanéen", "riz", "haricots", "street food"],
    productKeywords: ["riz", "haricot cornille", "poisson", "tomate", "plantain"],
    ingredients: [
      ingredient("Riz", "Rice", "600 g", "base"),
      ingredient("Haricots cornille", "Black-eyed peas", "300 g", "base"),
      ingredient("Feuilles de sorgho séchées", "Dried sorghum leaves", "quelques-unes", "spice", true),
      ingredient("Sauce tomate pimentée", "Spicy tomato stew", "500 ml", "side"),
      ingredient("Poisson ou œufs", "Fish or eggs", "au choix", "protein", true),
      ingredient("Plantain frit", "Fried plantain", "4", "side", true),
    ],
    steps: [
      l("Tremper les haricots si nécessaire puis les précuire.", "Soak the beans if needed, then par-cook them."),
      l("Ajouter les feuilles de sorgho pour colorer l'eau de cuisson.", "Add sorghum leaves to color the cooking water."),
      l("Incorporer le riz rincé et ajuster le liquide.", "Add the rinsed rice and adjust the liquid."),
      l("Cuire à couvert jusqu'à ce que riz et haricots soient tendres.", "Cook covered until both rice and beans are tender."),
      l("Servir avec sauce tomate et garnitures choisies.", "Serve with tomato stew and the chosen toppings."),
    ],
  },
  {
    slug: "doro-wat",
    name: l("Doro wat", "Doro wat"),
    aliases: ["wat de poulet", "ragoût éthiopien poulet"],
    country: "Éthiopie",
    region: "Hauts plateaux",
    category: "sauce",
    difficulty: "hard",
    timeMinutes: 110,
    servings: 6,
    description: l("Ragoût de poulet longuement mijoté aux oignons, au berbéré et au beurre épicé, garni d'œufs.", "Chicken stew slowly cooked with onions, berbere and spiced butter, finished with eggs."),
    tradition: l("Plat de fête servi sur injera ; les oignons sont cuits lentement avant l'ajout des matières grasses.", "A celebration dish served on injera; onions are cooked slowly before fat is added."),
    service: l("Déposer le ragoût sur l'injera et répartir les œufs autour du poulet.", "Spoon the stew onto injera and arrange the eggs around the chicken."),
    allergens: [l("Œufs", "Eggs"), l("Lait si beurre clarifié", "Milk if clarified butter is used")],
    tags: ["éthiopien", "poulet", "berbéré", "injera"],
    productKeywords: ["poulet", "berbere", "piment", "oignon", "oeuf", "injera"],
    ingredients: [
      ingredient("Poulet découpé", "Cut chicken", "1,5 kg", "protein"),
      ingredient("Oignons rouges", "Red onions", "1 kg", "vegetable"),
      ingredient("Mélange berbéré", "Berbere spice", "3 c. à soupe", "spice"),
      ingredient("Niter kibbeh ou beurre clarifié", "Niter kibbeh or clarified butter", "100 g", "fat"),
      ingredient("Œufs durs", "Hard-boiled eggs", "6", "protein"),
      ingredient("Ail et gingembre", "Garlic and ginger", "2 c. à soupe", "spice"),
    ],
    steps: [
      l("Faire compoter les oignons hachés à sec et à feu doux pendant 30 minutes.", "Cook the chopped onions dry over low heat for 30 minutes."),
      l("Ajouter le beurre épicé, le berbéré, l'ail et le gingembre.", "Add spiced butter, berbere, garlic and ginger."),
      l("Incorporer le poulet et l'enrober soigneusement de la base aromatique.", "Add the chicken and coat it thoroughly in the aromatic base."),
      l("Ajouter un peu d'eau et mijoter couvert jusqu'à tendreté.", "Add a little water and simmer covered until tender."),
      l("Inciser les œufs durs, les ajouter à la sauce et cuire encore dix minutes.", "Score the hard-boiled eggs, add them to the sauce and cook for another ten minutes."),
    ],
  },
  {
    slug: "poulet-moambe-saka-saka",
    name: l("Poulet moambe et saka-saka", "Moambe chicken with saka-saka"),
    aliases: ["poulet moambe", "moambe chicken", "saka saka"],
    country: "Congo",
    region: "Bassin du Congo",
    category: "main",
    difficulty: "medium",
    timeMinutes: 90,
    servings: 6,
    description: l("Poulet mijoté dans une sauce aux noix de palme, accompagné de feuilles de manioc pilées.", "Chicken simmered in palm nut sauce, served with pounded cassava leaves."),
    tradition: l("La moambe et le saka-saka forment un ensemble emblématique de plusieurs cuisines du bassin du Congo.", "Moambe and saka-saka form an emblematic pairing across several Congo Basin cuisines."),
    service: l("Servir avec riz blanc, chikwangue ou banane plantain.", "Serve with white rice, chikwangue or plantain."),
    allergens: [l("Poisson si utilisé dans le saka-saka", "Fish if used in the saka-saka")],
    tags: ["congolais", "noix de palme", "feuilles de manioc", "poulet"],
    productKeywords: ["poulet", "graine palme", "noix palme", "feuilles manioc", "chikwangue", "plantain"],
    ingredients: [
      ingredient("Poulet découpé", "Cut chicken", "1,5 kg", "protein"),
      ingredient("Concentré de noix de palme", "Palm nut concentrate", "700 g", "base"),
      ingredient("Feuilles de manioc pilées", "Pounded cassava leaves", "800 g", "vegetable"),
      ingredient("Oignons", "Onions", "3", "vegetable"),
      ingredient("Poisson fumé", "Smoked fish", "150 g", "protein", true),
      ingredient("Piment", "Chili", "1", "spice", true),
    ],
    steps: [
      l("Dorer le poulet assaisonné puis ajouter un oignon émincé.", "Brown the seasoned chicken, then add one sliced onion."),
      l("Diluer le concentré de palme, le filtrer si nécessaire et l'ajouter au poulet.", "Dilute the palm concentrate, strain if needed and add it to the chicken."),
      l("Mijoter 45 minutes jusqu'à épaississement de la moambe.", "Simmer for 45 minutes until the moambe thickens."),
      l("Cuire séparément les feuilles de manioc avec oignon et poisson fumé.", "Cook the cassava leaves separately with onion and smoked fish."),
      l("Prolonger la cuisson du saka-saka jusqu'à tendreté complète des feuilles.", "Continue cooking the saka-saka until the leaves are completely tender."),
      l("Servir les deux préparations avec l'accompagnement choisi.", "Serve both preparations with the chosen accompaniment."),
    ],
  },
];

const normalize = (value: string) =>
  value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();

const CATEGORY_LABELS: Record<CulinaryDish["category"], Localized> = {
  main: l("Plat complet", "Main dish"),
  sauce: l("Sauce et mijoté", "Sauce and stew"),
  grill: l("Braisé et grillade", "Grilled dish"),
  "street-food": l("Cuisine de rue", "Street food"),
};

export function searchDishLibrary({
  query = "",
  country = "",
  category = "",
  product = "",
  limit = 60,
}: {
  query?: string;
  country?: string;
  category?: string;
  product?: string;
  limit?: number;
}) {
  const normalizedQuery = normalize(query);
  const normalizedProduct = normalize(product);
  const queryTerms = normalizedQuery.split(/\s+/).filter((term) => term.length > 1);
  const productTerms = normalizedProduct.split(/\s+/).filter((term) => term.length > 2);

  return DISH_LIBRARY
    .map((dish) => {
      const searchable = normalize([
        dish.name.fr,
        dish.name.en,
        dish.aliases.join(" "),
        dish.country,
        dish.region,
        dish.description.fr,
        dish.description.en,
        dish.tags.join(" "),
        dish.productKeywords.join(" "),
        dish.ingredients.map((item) => `${item.name.fr} ${item.name.en}`).join(" "),
      ].join(" "));
      let score = dish.featured ? 2 : 0;
      for (const term of queryTerms) {
        if (searchable.includes(term)) score += 4;
        if (normalize(dish.name.fr).includes(term) || normalize(dish.name.en).includes(term)) score += 6;
      }
      for (const term of productTerms) {
        if (searchable.includes(term)) score += 5;
        if (dish.productKeywords.some((keyword) => normalize(keyword).includes(term) || term.includes(normalize(keyword)))) score += 8;
      }
      if (normalizedProduct && normalize(dish.country).includes(normalizedProduct)) score += 2;
      return { dish, score };
    })
    .filter(({ dish, score }) => {
      if (country && !normalize(dish.country).includes(normalize(country))) return false;
      if (category && dish.category !== category) return false;
      if (normalizedQuery && score <= (dish.featured ? 2 : 0)) return false;
      if (normalizedProduct && score <= (dish.featured ? 2 : 0)) return false;
      return true;
    })
    .sort((a, b) => b.score - a.score || Number(b.dish.featured) - Number(a.dish.featured) || a.dish.name.fr.localeCompare(b.dish.name.fr))
    .slice(0, Math.max(1, Math.min(limit, 100)));
}

export function localizeDish(dish: CulinaryDish, locale: DishLocale, score = 0) {
  return {
    slug: dish.slug,
    name: dish.name[locale],
    aliases: dish.aliases,
    country: dish.country,
    region: dish.region,
    category: dish.category,
    categoryLabel: CATEGORY_LABELS[dish.category][locale],
    difficulty: dish.difficulty,
    timeMinutes: dish.timeMinutes,
    servings: dish.servings,
    featured: Boolean(dish.featured),
    description: dish.description[locale],
    tradition: dish.tradition[locale],
    service: dish.service[locale],
    allergens: dish.allergens.map((item) => item[locale]),
    tags: dish.tags,
    recommendationScore: score,
    ingredients: dish.ingredients.map((item) => ({
      name: item.name[locale],
      quantity: item.quantity,
      role: item.role,
      optional: Boolean(item.optional),
    })),
    steps: dish.steps.map((step) => step[locale]),
  };
}

export function serializeDishTemplate(dish: CulinaryDish, score = 0) {
  return {
    slug: dish.slug,
    nameFr: dish.name.fr,
    nameEn: dish.name.en,
    country: dish.country,
    region: dish.region,
    category: dish.category,
    difficulty: dish.difficulty,
    timeMinutes: dish.timeMinutes,
    servings: dish.servings,
    featured: Boolean(dish.featured),
    descriptionFr: dish.description.fr,
    descriptionEn: dish.description.en,
    recommendationScore: score,
    ingredients: dish.ingredients.map((item) => ({
      nameFr: item.name.fr,
      nameEn: item.name.en,
      quantity: item.quantity,
      role: item.role,
      optional: Boolean(item.optional),
    })),
    stepsFr: dish.steps.map((step) => step.fr),
    stepsEn: dish.steps.map((step) => step.en),
  };
}
