/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false cloudflare-env.d.ts` (hash: 98c9ed0a9c58bf12dcb463a5128c031b)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCOUNT_ID: "82164eca9557f63e18984230deac12bc";
	CLOUDFLARE_DEPLOYMENT_TARGET: "workers";
	SUPABASE_URL: "https://ahigidhuhqcmxzjxetnw.supabase.co";
	DATABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
	NEXT_PUBLIC_SITE_URL: string;
	CLOUDFLARE_DOMAIN_STATUS: string;
	NEXT_PUBLIC_VAPID_PUBLIC_KEY: string;
	VAPID_PRIVATE_KEY: string;
	VAPID_SUBJECT: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_DEPLOYMENT_TARGET" | "SUPABASE_URL" | "DATABASE_URL" | "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" | "NEXT_PUBLIC_SITE_URL" | "CLOUDFLARE_DOMAIN_STATUS" | "NEXT_PUBLIC_VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY" | "VAPID_SUBJECT">> {}
}
